export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_ADD_SHIPPING_DETAILS = 'CART_ADD_SHIPPING_DETAILS';
export const CART_ADD_PAYMENT_METHOD = 'CART_ADD_PAYMENT_METHOD';